"""open questions: rubric, answer_text, feedback, nullable is_correct

Revision ID: d5ff3d243d7b
Revises: 34d8ab4b0ac0
Create Date: 2026-06-16 23:00:57.080448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ff3d243d7b'
down_revision: Union[str, Sequence[str], None] = '34d8ab4b0ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer_text', sa.Text(), nullable=True))
    op.add_column('answers', sa.Column('feedback', sa.Text(), nullable=True))
    op.alter_column('answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('questions', sa.Column('rubric', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'rubric')
    op.alter_column('answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('answers', 'feedback')
    op.drop_column('answers', 'answer_text')
    # ### end Alembic commands ###
